SC-2049: Language Upgrade - Java 11
project-sunbird/certificate-registry pull request #64
Opened 2020-10-06 10:37 UTC by aishwa8141

2020-10-06 10:57 UTC, PradyumnaNagendra approved these changes

2020-10-08 06:17 UTC, maheshkumargangula requested changes

2020-10-08 06:17 UTC, maheshkumargangula commented on service/pom.xml
>                      <target>1.8</target>
Remove these two lines

2020-10-08 06:43 UTC, aishwa8141 commented on service/pom.xml
>                      <target>1.8</target>
removed ...

2020-10-08 07:40 UTC, maheshkumargangula approved these changes

2020-10-08 07:41 UTC, merged