SB-29068 modified certificate download api wrto sunbird-rc integration
project-sunbird/certificate-registry pull request #77
Opened 2022-03-08 17:27 UTC by Hari-stackroute

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions: Java-11, play2-2.7.2
* Hardware versions: 2 CPU/ 4GB RAM

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-03-16 10:23 UTC, Hari-stackroute commented on all-actors/src/main/java/org/sunbird/RegistryCredential.java
> +    private  static final String CERTIFICATE_TYPE = getPropsFromEnvs("certificate_type");
change it to RC_ENTITY_TYPE

2022-03-16 10:26 UTC, reshmi-nair requested changes

2022-03-16 10:26 UTC, reshmi-nair commented on all-actors/src/main/java/org/sunbird/RegistryCredential.java
> +    private static final String DOWNLOAD_URI= "/rc/certificate/v1/download";
Change this url to service url and configure schema name as env variable

2022-03-16 10:26 UTC, reshmi-nair commented on all-actors/src/main/java/org/sunbird/RegistryCredential.java
> +        String esApi=String.format("http://%s:9200/%s/search",getPropsFromEnvs(SUNBIRD_ES_IP).split(",")[0],"   rc/certificate/v1");
change this to RC search url

2022-03-16 10:26 UTC, reshmi-nair commented on all-actors/src/main/java/org/sunbird/serviceimpl/CertsServiceImpl.java
> +                String templateUrl = rcJsonResponse.getBody().getObject().getJSONObject(JsonKeys.RESULT).getString("templateurl");
change to templateUrl and define jsonkey

2022-03-16 10:26 UTC, reshmi-nair commented on all-actors/src/main/java/org/sunbird/serviceimpl/CertsServiceImpl.java
> +                headerMap.put("templateurl", templateUrl);
jsonkey needed

2022-03-16 10:26 UTC, reshmi-nair commented on all-actors/src/main/java/org/sunbird/serviceimpl/CertsServiceImpl.java
> +                printUri =  rcDownloadJsonResponse.getBody().getObject().getJSONObject(JsonKeys.RESULT).getString(JsonKeys.PRINT_URI);
We will be getting svg image String. Check the current download folow from UI. set the string to print uri

2022-03-17 08:17 UTC, reshmi-nair approved these changes

2022-03-17 13:51 UTC, reshmi-nair approved these changes

2022-03-17 13:54 UTC, reshmi-nair approved these changes

2022-03-17 13:54 UTC, merged